language = "en"

[personal]
first_name = "Alberto"
last_name = "Lazari"

[personal.info]
linkedin = "alberto-lazari"
github = "alberto-lazari"
email = "alberto.lazari@gmail.com"

[lang.en]
header_quote = "Computer Science MSc student at Unipd"
cv_footer = "Curriculum vitae"
letter_footer = "Cover letter"

[layout]
awesome_color = "skyblue"

before_section_skip = "1.2em"
before_entry_skip = ".5em"
before_entry_description_skip = "0em"

[layout.header]
header_align = "center"
display_profile_photo = false
profile_photo_path = ""

[layout.entry]
display_entry_society_first = true
display_logo = true

[inject]
inject_ai_prompt = false
inject_keywords = true
injected_keywords_list = ["Programming Languages", "Android", "Java", "Python", "REST APIs"]
